// .github/workflows/ci.yml
name: Publish to GitHub Package Registry
on: [push]
jobs:
  build:
runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 8.x
        scope: '@arthas168'
    - name: yarn install, build, and test
      run: |
        yarn
        yarn test